$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: diabetes_training_01
description: Training Pipeline to train a diabetes model

# <inputs_and_outputs>
inputs:
  input: 
    type: uri_file
    path: azureml:diabetes_data_oh4ml@latest

outputs: 
#  prepared_data:
  trained_model:
#  predictions:
#  score_report:
#  deploy_flag:
# </inputs_and_outputs>

# <jobs>
settings:
  default_datastore: azureml:workspaceblobstore
  default_compute: azureml:demo-cpucluster1
  continue_on_step_failure: false

jobs:
  train_model:
    name: train_model
    display_name: train-model
    code: ../scripts
    command: >-
      python train-diabetes.py 
      --input_data ${{inputs.diabetes_data}} 
      --model_output ${{outputs.model_output}}
    environment: azureml:diabetes-env-02@latest
    inputs:
      diabetes_data: ${{parent.inputs.input}}
    outputs:
      model_output: ${{parent.outputs.trained_model}}

  register_model:
    name: register_model
    display_name: register-model
    code: ../scripts
    command: >-
      python register.py 
      --model_name ${{inputs.model_name}} 
      --model_path ${{inputs.model_path}} 
      --deploy_flag ${{inputs.deploy_flag}}
    environment: azureml:diabetes-env-02@latest
    inputs:
      model_name: diabetes_model_oh4ml
      model_path: ${{parent.jobs.train_model.outputs.model_output}}
      deploy_flag: 1

# </jobs>